### ISSUE TITLE
Exception bacen iz java.lang.Thread.run()

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp2019/ConstPlusPlus#2]
Nekada dobijem ovaj exception u nekim delovima aplikacije - verujem da je krivac pozadinska nit koja preuzima sadrzaj. Nisam uspeo da povezem da li izbor parametara ima veze sa bilo cim - desava se nasumicno nekada.

Stack trace:
```
java.io.IOException: Underlying input stream returned zero bytes
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at java.io.Reader.read(Reader.java:140)
	at org.jsoup.parser.CharacterReader.bufferUp(CharacterReader.java:53)
	at org.jsoup.parser.CharacterReader.consume(CharacterReader.java:98)
	at org.jsoup.parser.TokeniserState$34.read(TokeniserState.java:552)
	at org.jsoup.parser.Tokeniser.read(Tokeniser.java:57)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:51)
	at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:45)
	at org.jsoup.parser.Parser.parseInput(Parser.java:39)
	at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:153)
	at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:851)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:296)
	at scraper.ScraperKt$fetchCourseListTask$1.invoke(Scraper.kt:54)
	at scraper.ScraperKt$fetchCourseListTask$1.invoke(Scraper.kt)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by aleksandar-stefanovic** [comment]
Nisam uspeo da reprodukujem. Kroz commit d819723 je dodata provera oko mogućnosti da se pristupi stranici rasporeda, tako da je možda to popravilo ovaj bag.

**Comment by ivan-ristovic** [comment]
Da, pokretao sam vise puta i ne dobijam vise taj exception tako da pretpostavljam da je sve reseno - stoga zatvaram issue.
